on :
  push:
    branches :
      - master


jobs :
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'print folder contents before' 
        run: ls

      - uses: action/checkout@v3

      - name: 'print folder contents after'
        run: ls
